### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by nicholascw** [lyyyuna/bilibili_danmu#1]
Error message:

_Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    from bilibiliClient import bilibiliClient
  File "/home/nicholas/bilibili_danmu/bilibiliClient.py", line 26
    async def connectServer(self):
            ^
SyntaxError: invalid syntax_

**Using Kali Linux 2.0 with Python 3.5.1 <compiled version> together with pip 8.1.1**

**Comment by lyyyuna** [comment]
Hi, @wck963 
As 'async' is the keyword of Python 3.5, it should not raise syntax error. Can you double confirm that you have used the right version of Python?

**Comment by nicholascw** [comment]
It is okay now, I formerly used a 3.4 python and got a syntax error. So I chose to update to 3.5.1.....but it was still wrong... after I restarted my computer this morning it works

**Comment by lyyyuna** [comment]
@wck963 :)
