### ISSUE TITLE
Python3.4 和Python3.5 共存时,pip安装aiohttp问题

### ISSUE THREAD

**Issue by nicholascw** [lyyyuna/bilibili_danmu#2]
系统环境是Ubuntu 14.04.4,默认安装3.4.x,用官网源码包编译安装3.5.1,Python3命令的版本确认是3.5.1但提示没有aiohttp,用pip3安装提示 already satisfied.

**Comment by lyyyuna** [comment]
Hi, @wck963 
可以这样
python3 -m pip install aiohttp
确保使用的是 python3.5 的 pip
///////////////////////////////////////////////
你也可以看 pip3.5 这个命令存不存在

**Comment by Nevermore-Lee** [comment]
@lyyyuna 谢谢啊，解决了。
