### ISSUE TITLE
此项目有任何的license吗？

### ISSUE THREAD

**Issue by superfashi** [lyyyuna/bilibili_danmu#3]
想自己拿去写点特定的东西，有license需要遵守吗？
顺便，程序写得非常的好！

**Comment by lyyyuna** [comment]
@hanbang-wang 木有。拿去随用~

**Comment by lyyyuna** [comment]
@hanbang-wang 
https://www.fuckbilibili.com/ 这个网站他们还开发了更多的接口。

**Comment by lyyyuna** [comment]
@hanbang-wang 原来 fuckbilibili 是你啊~

**Comment by superfashi** [comment]
谢谢啊~我得去好好看看asycnio库hhh
