### ISSUE TITLE
关于未知原因出现‘utf-8 decode error’

### ISSUE THREAD

**Issue by ghost** [lyyyuna/bilibili_danmu#6]
在[此行中](https://github.com/lyyyuna/bilibili_danmu/blob/master/bilibiliClient.py#L103)，出现utf-8 decode error 是因为获取到的字节不完整，然而水平有限暂时无法找到原因，所以来通知作者
此外，在[此行中](https://github.com/lyyyuna/bilibili_danmu/blob/master/bilibiliClient.py#L119)，jsondecode失败也是因为获取到的字节不完整，虽然恰好可以在上面成功decode，但是decode出来的是不完整的json字符串，因此才会jsondecode

另：由于网络波动在某个循环里可能获取不到弹幕，作者可否增加个timeout的设定

多谢

**Comment by lyyyuna** [comment]
@unnamed5719 这是个演示性的工程，所以处理上不打算写太全。timeout，然后呢，我想只能断掉重连。

**Comment by beilunyang** [comment]
我也一直很困惑jsondecode这个问题，不知道两位大佬找到解决方案了没有....

**Comment by lyyyuna** [comment]
@beilunyang 像我代码里直接忽略这个异常即可，不影响下一次弹幕的解析。

**Comment by beilunyang** [comment]
@lyyyuna 直接忽略的话，难道不会导致有一条弹幕消息丢失

**Comment by lyyyuna** [comment]
@beilunyang 是的。获取到的json串本身就是不完整的，再尝试 decode 也没有意义。实际上，各直播平台自己的客户端（网页版flash，手机app），丢弹幕也是常有的事。。

**Comment by beilunyang** [comment]
@lyyyuna 这样啊，这个decode问题看得我好迷。谢谢大佬指教
